config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/home', to: 'static_pages#home'
  get '/membership', to: 'static_pages#membership'
  get '/application', to: 'members#new'
  post '/application', to: 'members#create'
  get '/benefits', to: 'static_pages#benefits'
  get '/pay', to: 'static_pages#pay'
  get '/handbook', to: 'static_pages#handbook'
  get '/handbook_download', to: 'static_pages#handbook_download'
  get '/meets', to: 'static_pages#meets'
  get '/calendar', to: 'static_pages#calendar'
  get '/meetslist', to: 'static_pages#ical_feed'
  get '/booking', to: 'static_pages#booking'
  get '/galleries', to: 'static_pages#galleries'
  get '/help', to: 'static_pages#help'
  get '/committee', to: 'static_pages#the_committee'
  get '/history', to: 'static_pages#history'
  get '/cae_amos', to: 'static_pages#cae_amos'
  get '/archives', to: 'static_pages#archives'
  get '/reports', to: 'static_pages#reports'
  get '/contact', to: 'static_pages#contact'
  get '/links', to: 'static_pages#links'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/login', to: 'static_pages#membership'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/update_attendee_status/:meet_id/:member_id', to: 'attendees#update_status', as: 'update_attendee_status'

  resources :password_resets, only: %i[new create edit update]

  resources :members do
    member do
      get 'emergency_contact', to: 'emergency_contact#edit'
      patch 'emergency_contact', to: 'emergency_contact#update'
      get 'meets', to: 'meets#edit'
      patch 'meets', to: 'meets#update'
      get 'attendees', to: 'attendees#index'
      patch 'attendees', to: 'attendees#update'
      delete 'attendees', to: 'attendees#destroy'
      get 'sign_up/:meet_id', to: 'attendees#new', as: :new_attendee
      post 'sign_up/:meet_id', to: 'attendees#create'
      patch 'email_subscribe', to: 'members#email_subscribe'
    end
  end

  namespace :committee do
    resources :emails
    get '/mailer/email_preview(/:id(.:format))', to: 'emails#email_preview', as: 'email_preview'
    get '/mailer/send_email(/:id(.:format))', to: 'emails#send_email', as: 'send_email'
    get 'past_meets', to: 'meets#past'
    resources :meets
    resources :attendees
    resources :members do
      collection do
        post :multiple
        patch :update_multiple
        get :edit_role
        patch :update_role
        get :export_all, to: 'members#all'
        get :export_bmc, to: 'members#for_bmc'
        post :export_checked, to: 'members#checked'
        get :download_file, to: 'members#download_file'
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'icalendar/tzinfo'
  require 'tzinfo'
  require 'open-uri'
  require 'nokogiri'

  include StaticPagesHelper
  include MeetsHelper

  # helper_method :find_meet_leader

  skip_before_action :session_expires
  # after_action :allow_youtube_iframe# only: :home

  def home
    @meets = next_meets
    @bb_feed = bb_feed
    @meta_description = meta_description('home')
  end

  def benefits
    @meta_description = meta_description('benefits')
  end

  def booking
    @meta_description = meta_description('booking')
  end

  def calendar
    @member = current_user if logged_in?
    @future_meets = all_future_meets
    @past_meets = past_meets
    @meta_description = meta_description('calendar')
  end

  def contact
    @meta_description = meta_description('contact')
  end

  def galleries
    @meta_description = meta_description('galleries')
  end

  def handbook
    @meta_description = meta_description('handbook')
  end

  def help
    @meta_description = meta_description('help')
  end

  def history; end

  def archives; end

  def cae_amos; end

  def links
    @meta_description = meta_description('links')
  end

  def meets
    @future_meets = all_future_meets
    @meta_description = meta_description('meets')
  end

  def membership
    @meta_description = meta_description('membership')
  end

  def pay
    @meta_description = meta_description('pay')
  end

  def privacy_policy
    @meta_description = meta_description('privacy_policy')
  end

  def the_committee
    @meta_description = meta_description('the_committee')
  end

  def handbook_download
    send_file(
      "#{Rails.root}/public/LMC-Constitution-and-Handbook-September-2019.pdf",
      filename: 'LMC Constitution and Handbook.pdf',
      type: 'application/pdf'
    )
  end

  # def allow_youtube_iframe
  #   response.headers['X-Frame-Options'] = 'ALLOW-FROM https://www.youtube.com/'
  # end
end

app/helpers/static_pages_helper.rb
require 'open-uri'

module StaticPagesHelper
  def meta_description(page)
    case page
    when 'home'
      'A group of like minded people from the Leeds area and beyond who enjoy doing stuff in the outdoors including walking, climbing, mountaineering, mountain biking, cycling, skiing, camping and anything else that sounds like fun.'
    when 'benefits'
      'There are plenty of reasons to join the Leeds Mountaineering Club. We have a busy calendar of meets, organised social events, BMC affiliate membership and discounts with local shops and national retailers.'
    when 'booking'
      'How to book on a meet with the Leeds Mountaineering Club. You must be a member before you can come on a hut meet.'
    when 'calendar'
      "We have meets organized all over the country, throughout the year, camping and in huts. There's loads to do!"
    when 'contact'
      "Get in touch with the Leeds Mountaineering Club. We're happy to answer any questions about the club and how to join."
    when 'galleries'
      'See photos of some of our previous meets and adventures.'
    when 'handbook'
      'The rules and regulations which govern the club and how it works.'
    when 'help'
      'Information on joining the club, signing up for a meet, finding us and using this website.'
    when 'links'
      'A list of useful links for leeds based climber, walkers and mountaineers.'
    when 'meets'
      'On the first Tueday of every month we head to a pub for a pint and chat. We also climb every Tuesday, at the wall in winter and outside in summer. '
    when 'membership'
      'There are two levels of membership, provisional and full, you need to attend three meets and demonstrate that you can conduct yourself safely to progress from provisional to full membership.'
    when 'pay'
      'Pay your subs online with Paypal or contact us for other ways to pay.'
    when 'the_committee'
      'We have a 10 member committee who meet throughout the year to run the club. The committee are voted in every year at our AGM.'
    end
  end

  def bb_feed
    openuri_params = {
      open_timeout: 3,
      read_timeout: 3
    }
    begin
      content = open('http://bb.leedsmc.org/bbfeed.php', openuri_params).read
    rescue StandardError => e
      puts e
      'Timed out waiting for response from http://bb.leedsmc.org/bbfeed.php.'
    else
      page = Nokogiri::HTML(content)
      links = page.css('a')
      page.search('//br/preceding-sibling::text()|//br/following-sibling::text()').each_with_index do |node, i|
        node.replace(Nokogiri.make("<p>#{links[i]}<br>#{node.to_html}</p>"))
      end
      page.css('p').to_s
    end
  end

  def date_display(date, nights = 0)
    final_night = (date + nights.to_i) - 1.days
    if nights.nil? || nights == 0
      date.strftime("#{date.day.ordinalize} %b %Y")
    elsif date.month == final_night.month
      date.strftime("#{date.day.ordinalize} ") + ' - ' + final_night.strftime("#{final_night.day.ordinalize} %b %Y")
    else
      date.strftime("#{date.day.ordinalize} %b ") + ' - ' + final_night.strftime("#{final_night.day.ordinalize} %b %Y")
    end
  end

  def ical_feed
    meets = all_future_meets
    @organiser = 'mailto:leedsmc@gmail.com'
    respond_to do |format|
      format.html
      format.ics do
        cal = Icalendar::Calendar.new
        filename = 'lmc-meets-calendar'
        cal.prodid = '-//LMC Meets Calendar//NONSGML v2.0//EN'
        cal.version = '2.0'
        filename += '.ics'

        meets.each do |m|
          description = "LMC #{m.meet_type.downcase} meet, #{m.location}."

          case m.meet_type
          when 'Hut'
            start_time = 'T200000'
            description += " #{m.number_of_nights} nights, #{m.places} places."
          when 'Camping'
            start_time = 'T200000'
            description += " #{m.number_of_nights} nights."
          when 'Evening'
            start_time = 'T180000'
            description += " #{m.activity}ing meet." if m.activity.present?
          when 'Day'
            start_time = 'T080000'
            description += " #{m.activity}ing meet." if m.activity.present?
            end

          if m.member.present?
            description += " The meet leader is #{m.member.first_name + ' ' + m.member.last_name}."
       end
          description += " Notes: #{m.notes}." if m.notes.present?
          if m.bb_url.present?
            description += " More information at #{m.bb_url}."
           end

          summary = "LMC #{m.meet_type.downcase} meet, #{m.location}."
          summary += " #{m.activity}ing meet." if m.activity.present?

          end_time = 'T220000'
          start_date = m.meet_date.strftime('%Y%m%d') + start_time
          end_date = (m.meet_date + m.number_of_nights.to_i - 1.days).strftime('%Y%m%d') + end_time

          tzid = 'Europe/London'
          tz = TZInfo::Timezone.get tzid

          meet_start = Icalendar::Values::DateTime.new start_date, 'tzid' => tzid
          meet_end = Icalendar::Values::DateTime.new end_date, 'tzid' => tzid

          timezone = tz.ical_timezone meet_start
          cal.add_timezone timezone

          event = Icalendar::Event.new
          event.dtstart = meet_start
          event.dtend = meet_end
          event.description = description
          event.summary = summary
          event.location = m.location
          event.organizer = @organiser

          if m.member.present?
            meet_leader = m.member.first_name + ' ' + m.member.last_name
            event.organizer = Icalendar::Values::CalAddress.new(@organiser, cn: 'Meet Leader: ' + meet_leader)
          else
            event.organizer = Icalendar::Values::CalAddress.new(@organiser, cn: 'Meet Leader: TBC')
            end
          cal.add_event(event)
        end

        cal.publish
        send_data cal.to_ical, type: 'text/calendar', disposition: 'attachment', filename: filename
      end
    end
  end
end

app/views/static_pages/_meets_calendar.html.erb
<div class="meets-cal">
	<div class="table-responsive">
		<table class="table table-condensed" id="calendar">
			<thead>
				<tr>
					<td>Date</td>
					<td>Meet & Leader</td>
					<td>Info</td>
				</tr>
			</thead>
			<tbody>
				<% meets.each do |m| %>
					<% meet_leader = find_meet_leader(m) %>
					<tr id="<%= m.meet_type.downcase %>">
						<td><%= date_display(m.meet_date, m.number_of_nights) %></td>
						<td>
							<%= m.meet_type %> Meet. <% unless m.places.nil? %><%= m.places %> places.<% end %><br>
							<%= m.location %><% if m.activity.present? %> (<%= m.activity %>)<% end %><br>
							Meet Leader: 
							<% if meet_leader %>
								<%= meet_leader.first_name %> <%= meet_leader.last_name %>
							<% else %>
								TBC
							<% end %>
						</td>
						<td>
							<% if m.notes %><%= m.notes %><br/><% end %>
							<% if @member%>
								<% if !m.opens_on.nil?%>
                  <% if m.opens_on.future? %>
                    Opens on <%= format_date(m.opens_on) %>
                  <% else %>
                    <%= link_with_arrow(new_attendee_member_path(@member, m), "Sign Up!") %>
                  <% end %>
                <% end %>
							<% else %>
								<%= link_with_arrow(login_path, "Log in to sign up!") %>
							<% end %>
							<% if m.bb_url.present? %><br/><%= link_with_arrow(m.bb_url, "Bulletin Board Thread") %><% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/static_pages/help.html.erb
<div id="carousel-container">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("banners/help.jpg") %>
    </div>
  </div>
</div>

<div id="main" class="home">
	<div class="row row-top">
		<div class="container">
			<h2 style="margin-left: 15px">How do I...</h2>
				<div class="col-md-6 col-xs-12 spaced-left">
					<h3>Join the LMC?</h3>
					<p>First thing to do is to fill out the application form. Once you've done this find a meet you'd like to go on and come along!</p>
					<p>We organise the meets on the <%= link_to "Bulletin Boards", bb_url %>, so you should register to use them and post on the thread of the meet you want to come along to. You need to have paid the membership fee to come to weekend meets.</p>
					<%= link_to "Application Form", application_path, class: "btn btn-lg user-btn" %>
				</div>
				<div class="col-md-6 col-xs-12 spaced-right">
					<div class="side-img">
						<%= image_tag("pages/help-1.jpg") %>
					</div>
				</div>
		</div>
	</div>
	<div class="row row-mid">
		<div class="container">
				<div class="col-md-6 col-xs-12 spaced-left">
					<h3>Find Club Members on a Meet?</h3>
					<p>If you're looking for us at the Leeds Wall the best thing to do is to ask a Leeds Wall staff member - they know who many members are.</p>
					<p>For meets not at Leeds Wall it's best to post up on the bulletin boards as a meeting time and place will be set there.</p>
					<p>If all else fails look out for Leeds Mountaineering Club (LMC) T shirts and hoodies!</p>
					<p>There's more information on what we do and where we meet on the <%= link_to "meets page", meets_path %>.</p>
				</div>
				<div class="col-md-6 col-xs-12 spaced-right">
					<h3>Update My Details?</h3>
					<p>If you're already a member then you should be able to log into your account on this website to update your details. Just click log in at the top right to go to the login page.</p>
					<p>If you're forgotten your password we have a handy password reset link which will email you a temporary password to access your account.</p>
					<p>Note: the bulletin boards have a separate log in and register function to this site.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row row-btm">
		<div class="container">
				<div class="col-md-6 col-xs-12 spaced-left">
					<div class="side-img">
						<%= image_tag("pages/help-2.jpg") %>
					</div>
				</div>
				<div class="col-md-6 col-xs-12 spaced-right">
					<h3>Sign Up for a Meet?</h3>
					<p>For evening, day and camping meets there is no official sign up process as there are no limits on numbers. It is a good idea to register your interest on the bulletin board so that the meet leader knows who to expect.</p>
					<p>If you want to go on a hut meet you do have to book in advance. To make hut meets equally accessible for all members there are some rules around booking. See the <%= link_to "Booking on a Meet", booking_path %> page for more information.</p>
				</div>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div id="carousel-container">
<!-- Carousel -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("banners/home-1.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banners/home-2.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banners/home-3.jpg") %>
    </div>
  </div>

  <!-- Left and right controls -->
	  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
</div>
<!-- End Carousel -->

<div id="main" class="home">
	<div class="row row-top">
		<div class="container">
			<div class="row-elements">
				<div class="col-md-7 col-xs-12">
					<div class="home-main-description">
					<h2>Leeds Mountaineering Club</h2>
						<p>The Leeds Mountaineering Club (LMC) is an inclusive club for 
						anyone who enjoys the mountains for walking, climbing, running, 
						mountain biking, skiing or any other adventurous activity you can think of.</p>

						<p>The LMC welcomes all abilities, from complete novice hikers, 
						to highly experienced climbers. Our members come from all walks of life, with 
						varying levels of experience in the mountains.</p>

						<p>Hut or camping meets in mountainous regions of the UK (and occasionally 
						abroad) happen every other weekend. They are great, social events where hikers, 
						climbers, mountain bikers and the like can join up and enjoy the great outdoors
						together.</p>

						<p>There is an active group of climbers in the club who meet every Tuesday at The 
						Leeds Wall (winter/rainy days) or every Thursday at The Depot (all year round). When the summer months come along, there is a weekly outdoor climbing meet 
						at a chosen climbing spot on Tuesday evenings and includes a pub visit afterwards
						- locations can be found on the meets calendar.</p>

						<p>One Tuesday a month is dedicated to new members, and is a great way to meet 
						people and find out a bit more about the club before joining.</p>
					</div>
					<%= link_to "Members Log In", login_path, class: "btn btn-lg btn-default user-btn" %>
				</div>
			
				<div class="col-md-5 col-xs-12">
					<div class="side-box">
						<h4>Latest bulletin board posts:</h4>
						<%= sanitize @bb_feed %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row row-mid">
		<div class="container">
			<div class="row-elements">
				<div class="col-md-6 col-xs-12">
					<div class="side-img">
						  <%= content_tag(:iframe, '', src: 'https://www.youtube.com/embed/08YVKU4wyMs', width: 560, height: 315, frameborder: 0, allowfullscreen:"allowfullscreen") %>
					</div>
				</div>
				<div class="col-md-6 col-xs-12">
					<div class="home-main-description">
						<h2>Why Join the LMC?</h2>
						<p>Joining the LMC is easy and comes with a whole bunch of benefits:</p>
						<ul>
							<li>Discounts at a number of UK outdoor equipment shops</li>
							<li>Frequent trips and meets - UK and International</li>
							<li>Meet like-minded people who enjoy the outdoors</li>
							<li>Access to a large network of affliated club huts at a reasonable cost, in fantastic locations</li>
							<li>BMC affiliate membership</li>
							<li>Something for everyone - hiking, climbing and more.</li>
						</ul>
						<p>There are no prerequisites in terms of ability for membership, we only ask that all members act responsibly regarding safety so you can enjoy your chosen activity at the level you want.</p>
					</div>
					<%= link_to "More About Joining", benefits_path, class: "btn btn-lg btn-default user-btn" %>
				</div>
			</div>
		</div>
	</div>
	<div class="row row-btm">
		<div class="container">
			<div class="row-elements">
				<div class="col-md-6 col-xs-12">
					<div class="home-main-description">
						<h2>Meets</h2>
						<p>During the Summer months, there are Tuesday outdoor climbing meets at local crags and weekend camping meets in a variety of UK locations. During the winter months there are hut meets in affiliate club huts.<!-- Take a look at what members got up to on some of our past meets <b><%= link_to "here", '#' %></b>.--></p>
						<p>In addition to this, there are a variety of day walks and day climbs 
						throughout the year. The LMC also puts on talks and social events 
						which members are free to come along to and are very popular.</p>
						<p>You can find more information about our future meets and social 
						events by clicking below or visiting the bulletin board for more info.</p>
					</div>
					<%= link_to "When and Where we Meet", meets_path, class: "btn btn-lg btn-default user-btn" %>
				</div>
				<div class="col-md-6 col-xs-12">
					<div class="mini-meets-cal">
						<h2>Upcoming Meets</h2>
						<div class="table-responsive">
							<table class="table table-condensed" id="calendar">
								<tbody>
									<% @meets.first(4).each do |m| %>
										<% meet_leader = find_meet_leader(m) %>
										<tr>
											<td><%= date_display(m.meet_date, m.number_of_nights) %></td>
											<td id="col-two">
												<%= m.location %>
												<% if m.activity.present? %>
													(<%= m.activity %>)
												<% end %><br>
												Meet Leader: 
												<% if meet_leader %>
													<%= meet_leader.first_name %> <%= meet_leader.last_name %>
												<% else %>
													TBC
												<% end %>
												<% if m.bb_url.present? %>
													<%= link_to 'Bulletin Board Thread', m.bb_url %>
												<% end %>
											</td>
										</tr>
									<% end %>
								</tbody>
							</table>
						</div>
						<p style="margin: 5px 0 0 0; display: inline-block;"><%= link_to "View Full Meets Calendar", calendar_path %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/meets.html.erb
<div id="carousel-container">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
		<div class="carousel-inner">
	    <div class="item active">
	      <%= image_tag("banners/meets.jpg") %>
	    </div>
		</div>
	</div>
</div>

<div id="main" class="home">
	<div class="row row-top">
		<div class="container">
			<h2 id="title">When and Where We Meet</h2>
			<div class="col-md-6 col-xs-12 spaced-left">
				<h3>Summer</h3>
				<h4>Evenings</h4>
				<p>From April to October we meet every Tuesday evening at a local crag, if it's raining then many of us us will head to the Leeds Wall or The Depot. On the first Tuesday of every month the meet is always to Almscliff crag. After climbing we usually go to a nearby pub, for the first Tuesday at Almscliff this is dedicated a new members social and is held in the Hunters Inn near Pool in Wharfedale (unless it's raining).</p>
				<h4>Weekends</h4>
				<p>From May to October we have one or two camping meets per month to somewhere mountainous in the UK with walking, climbing and scrambling being the main activities undertaken by members. We also have regular walking and climbing meets on Saturdays or Sundays, often to the Peak District or the Yorkshire Dales. There are also occaisional hut meets during the summer months.</p>
				<%= link_to "More About Joining", benefits_path, class: "btn btn-lg btn-default user-btn" %>
			</div>
			<div class="col-md-6 col-xs-12 spaced-right">
				<h3>Winter</h3>
				<h4>Evenings</h4>
				<p>From October to April we meet every Tuesday evening at the Leeds Wall. On the first Tuesday of every month we head to the Midnight Bell in Leeds from 9pm for our new members social. To climb with us at Leeds Wall you'll need to be able to belay and have your own shoes and harness.</p>
				<h4>Weekends</h4>
				<p>From October to May we have one or two hut meets per month to somewhere mountainous in the UK with climbing and scrambling being the main activities undertaken by members. We also have regular walking meets Saturdays or Sundays, often to the Peak District or the Yorkshire Dales.</p>
				<p>Meet cancellations and changes (usually due to the weather) are always advertised on the relevant Bulletin Board thread.</p>
			</div>
		</div>
	</div>
	<div class="row row-mid"><a name="top"></a> 
		<div class="container">
			<div class="row-elements">
				<div class="col-md-12">
					<h2>Upcoming Meets</h2>
					<p>Don't miss a thing! We have a <a href="#icalfeed">calendar feed</a> for most calendar apps on Apple and Android.</p>
					<%= render partial: 'meets_calendar', locals: {meets: @future_meets} %>
					<%= link_to "Full Calendar", calendar_path, class: "btn btn-lg btn-default user-btn" %>
					<br>
					<br>
					<p><a href="#top">back to top</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="row row-btm">
		<div class="container">
			<div class="row-elements">
				<div class="col-md-6 col-xs-12 spaced-left">
					<h2>iCalendar Feed</h2><a name="icalfeed"></a>
					<p><a href="#top">back to top</a></p>
					<p>For those of you who use Google Calendar (or anything else that accepts iCalendar format) you can subscribe to the meets list using the following url: </br><strong><%= meetslist_url + ".ics"%></strong></p>
					<p>Eg. If you use Google Calendar</p>
					<ul>
						<li>Open your "Calendar"</li>
						<li>Click the "+" next to Add a friend's calendar</li>
						<li>Click "from URL"</li>
						<li>In the "URL of calendar" field paste <strong><%= meetslist_url + ".ics"%></strong></li>
					</ul>
					<p>Calendar times in the iCal feed are set only as a guide. Refer to the Bulletin Board for accurate start and finish times.</p>
				</div>
				<div class="col-md-6 col-xs-12 spaced-right">
					<div class="side-img">
						<%= image_tag("pages/meets-1.jpg") %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/membership.html.erb
<div id="carousel-container">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("banners/membership.jpg") %>
    </div>
  </div>
</div>

<div class="row row-top row-btm">
	<div class="container">
		<div class="col-md-6">
			<div class="membership main-box left">
				<h2>Join the Club or Log In</h2>
				<% if logged_in? %>
					<% controller.redirect_to member_path(@current_user) %>
				<% else %>	
					<p>To join the club fill out the application form by clicking the link below.</p>
					<%= link_to "Application Form", application_path, class: "btn btn-lg user-btn" %> 
					<p><br>If you're already a member then you can log in below.</p>
					<% flash.each do |message_type, message| %>
	          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	        <% end %>
					<%= form_for(:session, url: login_path) do |f| %>
						<%= f.label :email %>
						<%= f.email_field :email, class: 'form-control login-page' %>
						<%= f.label :password %>
						<%= link_to "(forgotten password)", new_password_reset_path %>
						<%= f.password_field :password, class: 'form-control login-page' %>
						<%= f.submit "Log in", class: 'btn btn-lg user-btn', style: 'width:inherit' %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="col-md-6">
			<div class="main-box right">
				<h2>Looking for more information?</h2>
				<h4>Who can join?</h4>
				<p>Anyone interested in getting outdoors to go walking, climbing and mountaineering with other like minded people. We don't set limitations on experience to become a member, however we do expect you to be able to enjoy your chosen activity safely. For more information go to <%= link_to "Why Join?", benefits_path %></p>
				<h4>How do I find you?</h4>
				<p>For information on when and where we meet check out the <%= link_to "Meets", meets_path %> page.</p>
				<h4>How much does it cost?</h4>
				<p>Membership will be £25 from 1st January 2021. See <%= link_to "Membership Fees", pay_path %>.</p>
				<h4>I'm still not sure...</h4>
				<p>If you have any questions which aren't answered on the site or just want to check that we're real and friendly people (we are) you can drop us an email. Our details are on the <%= link_to "Contact Us", contact_path %> page.</p>
			</div>
		</div>
	</div>
</div>