config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/home', to: 'static_pages#home'
  get '/membership', to: 'static_pages#membership'
  get '/application', to: 'members#new'
  post '/application', to: 'members#create'
  get '/benefits', to: 'static_pages#benefits'
  get '/pay', to: 'static_pages#pay'
  get '/handbook', to: 'static_pages#handbook'
  get '/handbook_download', to: 'static_pages#handbook_download'
  get '/meets', to: 'static_pages#meets'
  get '/calendar', to: 'static_pages#calendar'
  get '/meetslist', to: 'static_pages#ical_feed'
  get '/booking', to: 'static_pages#booking'
  get '/galleries', to: 'static_pages#galleries'
  get '/help', to: 'static_pages#help'
  get '/committee', to: 'static_pages#the_committee'
  get '/history', to: 'static_pages#history'
  get '/cae_amos', to: 'static_pages#cae_amos'
  get '/archives', to: 'static_pages#archives'
  get '/reports', to: 'static_pages#reports'
  get '/contact', to: 'static_pages#contact'
  get '/links', to: 'static_pages#links'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/login', to: 'static_pages#membership'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/update_attendee_status/:meet_id/:member_id', to: 'attendees#update_status', as: 'update_attendee_status'

  resources :password_resets, only: %i[new create edit update]

  resources :members do
    member do
      get 'emergency_contact', to: 'emergency_contact#edit'
      patch 'emergency_contact', to: 'emergency_contact#update'
      get 'meets', to: 'meets#edit'
      patch 'meets', to: 'meets#update'
      get 'attendees', to: 'attendees#index'
      patch 'attendees', to: 'attendees#update'
      delete 'attendees', to: 'attendees#destroy'
      get 'sign_up/:meet_id', to: 'attendees#new', as: :new_attendee
      post 'sign_up/:meet_id', to: 'attendees#create'
      patch 'email_subscribe', to: 'members#email_subscribe'
    end
  end

  namespace :committee do
    resources :emails
    get '/mailer/email_preview(/:id(.:format))', to: 'emails#email_preview', as: 'email_preview'
    get '/mailer/send_email(/:id(.:format))', to: 'emails#send_email', as: 'send_email'
    get 'past_meets', to: 'meets#past'
    resources :meets
    resources :attendees
    resources :members do
      collection do
        post :multiple
        patch :update_multiple
        get :edit_role
        patch :update_role
        get :export_all, to: 'members#all'
        get :export_bmc, to: 'members#for_bmc'
        post :export_checked, to: 'members#checked'
        get :download_file, to: 'members#download_file'
      end
    end
  end
end

app/models/meet.rb
class Meet < ApplicationRecord
	has_many :attendees, dependent: :destroy
	has_many :members, :through => :attendees

	accepts_nested_attributes_for :attendees

	MEET_TYPES = ["Hut", "Camping", "Day", "Evening"]

	validates :number_of_nights, numericality: { only_integer: true, allow_nil: true }
	validates :meet_type, presence: true, inclusion: { in: MEET_TYPES }
	validates :location, presence: true, length: { maximum: 200 }
	validates :places, numericality: {only_integer: true, allow_nil: true}
end

app/controllers/committee/attendees_controller.rb
class Committee::AttendeesController < Committee::BaseController
  skip_before_action :committee_member
  before_action :committee_member_or_meet_leader

  include MeetsHelper

  def create
    @meet = Meet.find(attendee_params[:meet_id])
    @attendee = @meet.attendees.create(attendee_params)
    if @attendee.save
      flash[:success] = 'Attendee added'
      redirect_to edit_committee_meet_path(@meet)
    else
      flash[:danger] = @attendee.errors.full_messages.to_sentence
      redirect_to edit_committee_meet_path(@meet)
    end
  end

  def update
    meet = Meet.find(params[:id])
    attendee = Attendee.find(attendee_params[:attendee_id])
    if params[:update_paid]
      attendee.toggle!(:paid)
      return redirect_to edit_committee_meet_path(meet)
    end
    if params[:update_meet_leader]
      unless attendee_params[:meet_leader_attendee] == ''
        old_meet_leader = Attendee.find(attendee_params[:meet_leader_attendee])
        old_meet_leader.update_attributes!(is_meet_leader: false)
      end
      attendee.update_attributes!(is_meet_leader: true)
      redirect_to edit_committee_meet_path(meet)
    end
  end

  def destroy
    attendee = Attendee.find(attendee_params[:attendee_id])
    attendee.destroy
    redirect_to edit_committee_meet_path
  end

  private

  def attendee_params
    permitted_params = params.require(:attendee).permit(
      :attendee_id,
      :member_id,
      :meet_id,
      :is_meet_leader,
      :sign_up_date,
      :paid,
      :meet_leader_attendee
    )
    permitted_params[:status] = 'pending'
    permitted_params
  end

  # before_filters

  def committee_member_or_meet_leader
    if logged_in?
      @member = Member.find(session[:member_id])
      unless committee_member?(@member) || meet_leader?(@member, @meet)
        flash[:danger] = 'Restriced Access.'
        redirect_to membership_path
      end
    else
      redirect_to root_url
    end
  end
end

app/controllers/committee/base_controller.rb
class Committee::BaseController < ApplicationController
  before_action :logged_in_member
  before_action :committee_member
  
	include MembersHelper
	
	private

	#before filters
		
	def committee_member
    if logged_in? #true when logged in
      @member = Member.find(session[:member_id])
      unless committee_member?(@member)
        flash[:danger] = "Restriced Access."
        redirect_to membership_path
      end
    else
      redirect_to root_url
    end
  end

  def remember_selected
    session[:members_to_edit] = params[:selected]
  end

  def recall_selected(members)
    if session[:members_to_edit]
      members.each { |m| m.selected = true if session[:members_to_edit].include?(m.id.to_s) }
    end
    session.delete(:members_to_edit)
  end

  def clear_selected(members)
    members.each { |m| m.selected = false }
    session.delete(:members_to_edit)
  end

  def saved_sort_or(default)
    session[:forwarding_url] || default
    session.delete(:forwarding_url)
  end
end

app/controllers/committee/emails_controller.rb
class Committee::EmailsController < Committee::BaseController
  include EmailsHelper

  def new
    @template = template
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email.save
      flash[:success] = "Email Saved"
      redirect_to edit_committee_email_path(@email)
    else
      flash[:danger] = "Error, email not saved."
      render 'new'
    end
  end

  def index
    @emails = Email.where("default_template = ?", false).order(sent_on: :DESC, updated_at: :DESC)
    @welcome_email = Email.find_by_default_template_and_template(true, "welcome")
  end

  def edit
    @email = Email.find(params[:id])
    @template = @email
  end

  def show
    @email = Email.find(params[:id])
  end

  def update
    @email = Email.find(params[:id])
    @template = @email
    unless @email.default_template == true && @email.template != "welcome"
      if @email.update_attributes(email_params)
        flash.now[:success] = "Email updated"
        render 'edit'
      else
        flash.now[:danger] = "Something went wrong. Email not updated."
        render 'edit'
      end
    else
      flash.now[:danger] = "Cannot overwrite default template."
      render 'edit'
    end
  end

  def email_preview
    @email = Email.find(params[:id])
    @recipient = @email.member || @member
    render :file => 'member_mailer/newsfeed.html.erb', :layout => 'mailer'
  end

  def send_email
    sent_to = 0
    @email = Email.find(params[:id])
    recipients
    @recipients.each do |rec|
      MemberMailer.newsfeed(rec, @email).deliver_later
      sent_to += 1
    end
    @email.update_columns(sent_to: sent_to, sent_on: DateTime.now)
    flash[:success] = "Sending Emails..."
    redirect_to committee_emails_path
  end

  def destroy
  end

  private

  def email_params
    params.require(:email).permit(:member_id,
                                  :template,
                                  :style,
                                  :subject,
                                  :body)
  end
end

app/controllers/committee/meets_controller.rb
class Committee::MeetsController < Committee::BaseController
  helper_method :find_meet_leader

  include MeetsHelper

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    if @meet.save
      save_attendee unless attendee_params[:member_id].nil?
      flash[:success] = 'Meet created'
      redirect_to committee_meets_path
    else
      render 'new'
    end
  end

  def index
    @future_meets = all_future_meets
  end

  def past
    @past_meets = Meet.where('meet_date < ?', Date.today).all.order(meet_date: :desc)
  end

  def edit
    create_values_for_edit
  end

  def update
    @meet = Meet.find(params[:id])
    if @meet.update_attributes(meet_params) && save_attendee
      flash[:success] = 'Meet updated'
    end
    create_values_for_edit
    render 'edit'
  end

  def destroy
    meet = Meet.find(params[:id])
    Attendee.where(meet_id: meet.id).destroy_all
    meet.destroy
    flash[:success] = 'Meet deleted.'
    redirect_to committee_meets_path
  end

  private

  def meet_params
    params.require(:meet).permit(:meet_date,
                                 :location,
                                 :bb_url,
                                 :meet_type,
                                 :number_of_nights,
                                 :places,
                                 :activity,
                                 :notes,
                                 :opens_on)
  end

  def attendee_params
    params.require(:attendees).permit(:member_id)
  end

  def create_values_for_edit
    @meet = Meet.find(params[:id])
    @meet_leader = find_meet_leader(@meet)
    if @meet_leader
      @meet_leader_attendee = @meet_leader.attendees.where(meet_id: @meet.id).first
    end
    @meet_attendees = @meet.attendees.where(is_meet_leader: false).order(sign_up_date: :asc)
    attendee_member_ids = @meet_attendees.map { |attendee| attendee.member.id }
    attendee_member_ids.push(@meet_leader.id) if @meet_leader
    @remaining_members = Member.where.not(id: attendee_member_ids).order(first_name: :asc)
    unless @meet.places.nil?
      @meet_has_reserves = @meet_leader ? @meet_attendees.length + 1 > @meet.places : @meet_attendees.length > @meet.places
    end
    @new_attendee = Attendee.new
  end

  def save_attendee
    attendee = Attendee.create(
      meet_id: @meet.id,
      member_id: attendee_params[:member_id],
      is_meet_leader: true,
      paid: false,
      status: 'confirmed',
      sign_up_date: Date.today
    )
    attendee.save
  end
end

app/controllers/committee/members_controller.rb
class Committee::MembersController < Committee::BaseController
	helper_method :sort_column, :sort_direction
	
	include MembersExports
	include MembersMultiple

	def index
		@members = Member.joins(:membership).order("#{sort_column} #{sort_direction}")
		recall_selected(@members)
	end

	def show
		remember_selected
		@member = Member.find(params[:id])
	end

	def edit
		remember_selected
		@member_to_edit = Member.find(params[:id])
	end

	def update
  	@member_to_edit = Member.find(params[:id])
  	if @member_to_edit.update_attributes(member_params)
  		flash[:success] = "Member updated"
      redirect_to committee_members_path
  	else
  		render 'edit'
  	end
  end

  def multiple
  	remember_selected
  	if params[:selected].nil?
	  	flash[:danger] = "No members selected."
	  	@members = Member.joins(:membership).order("#{sort_column} #{sort_direction}")
	  	redirect_to committee_members_path
	  	return
	  else
	  	case route_to params
	  	when :edit
	  		edit_multiple
	  	else
	  		export
	  	end
	  end
  end

  def edit_role
		@members = Member.joins(:membership).order("#{sort_column} #{sort_direction}")
		@committee_positions_list = committee_positions_list
  end

  def update_role
  	@member_to_assign_role = Member.find(params[:id])
  	@member_to_remove_role = Member.joins(:membership).find_by(memberships: {committee_position: params[:membership][:committee_position]})
  	if params[:membership][:committee_position] == "- remove role -"
  		if @member_to_assign_role.membership.update_attributes!(committee_position: nil)
  			flash[:success] = "#{@member_to_assign_role.first_name} #{@member_to_assign_role.last_name} is no longer on the committee"
  		end
  	else
  		@member_to_remove_role.membership.update_attributes!(committee_position: nil) unless @member_to_remove_role.nil?
  	end
  	
  	if @member_to_assign_role.membership.update_attributes(roles_params)
  		flash[:success] = "#{@member_to_assign_role.first_name} #{@member_to_assign_role.last_name} is now the #{@member_to_assign_role.membership.committee_position}"
  	else
  		flash.now[:danger] = "Failed to assign role. Pleae try again or contact the site admin."
  	end
		redirect_to saved_sort_or(committee_members_path)
  end

  def destroy
  	Member.find(params[:id]).destroy
  	flash[:success] = "Member removed from database."
  	redirect_to committee_members_path
  end
end

private

def member_params
	params.require(:member).permit(:address_1,
	  														 :address_2,
	  														 :address_3,
	  														 :town,
	  														 :postcode,
	  														 :country,
	  														 :phone,
	  														 :email,
	  														 :dob,
	  														 :bb_name,
	  															membership_attributes: [
	  																:bmc_number, 
	  																:membership_type, 
	  																:welcome_pack_sent,
	  																:fees_received_on, 
	  																:notes, 
	  																:id ]
	  														)
	end

	def membership_params
		params.require(:membership).permit(:bmc_number, :membership_type, :welcome_pack_sent,:fees_received_on, :notes)
	end

	def roles_params
		params.require(:membership).permit(:committee_position)
	end

	def sort_column(default="last_name")
		if 
			Member.column_names.include?(params[:sort])
			return params[:sort]
		elsif 
			Membership.column_names.include?(params[:sort])
			return params[:sort]
		else
			default
		end
	end

	def sort_direction(default = "asc")
		%w[asc desc].include?(params[:direction]) ? params[:direction] : default
	end

	def route_to params
		params[:route_to].keys.first.to_sym unless params[:route_to].nil?
	end

	def committee_positions_list
		["Chair",
		"Treasurer",
		"Meets Secretary",
		"Membership Secretary",
		"Communications Secretary",
		"Social Secretary",
		"Climbing Co-ordinator",
		"Walking Co-ordinator",
		"Ordinary Member",
		"Extra Ordinary Member",
		"Member Without Portfolio",
		"",
		"site admin",
		"- remove role -"]
	end

app/controllers/committee/welcome_message_controller.rb
class Committee::WelcomeMessageController < ApplicationController

	def edit
	end

	def update
	end
end

app/helpers/members_helper.rb
module MembersHelper

	def membership_level(member)
		if member.membership.committee_position
			"#{member.membership.committee_position}"
		else
			"#{member.membership.membership_type} Member"
		end
	end

	def committee_member?(member)
		!member.membership.committee_position.nil?
	end

	def latest_update(member)
		update = [member.updated_at, member.membership.updated_at].max
		update.strftime("%d/%m/%Y")
	end

	def created_at(member)
		member.created_at.strftime("%d/%m/%Y")
	end

	def updated_at(member)
		member.updated_at.strftime("%d/%m/%Y")
	end

	def new_member?(member)
		membership_level(member) == "Provisional (unpaid) Member"
	end

	def em_contact?(member)
		true if member.emergency_contact.primary_phone.nil?
	end
end

app/views/committee/members/edit_role.html.erb
<% provide(:title, @member.first_name + " " + @member.last_name) %>
<div class="top-border"></div>
<div class="row row-top">
	<div class="container">
		<h1>Assign Committee Roles</h1>
		<p><%= back_link(members_path(@member)) %></p>
		<% flash.each do |message_type, message| %>
			  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
		<% end %>

		<table class="table table-hover table-narrow">
			<thead>
				<th><%= sort_link "first_name", title: "First Name", link_path: edit_role_committee_members_path %></th>
				<th><%= sort_link "last_name", title: "Last Name", link_path: edit_role_committee_members_path %></th>
				<th><%= sort_link "address_1", title: "Address", link_path: edit_role_committee_members_path %></th>
				<th><%= sort_link "email", title: "Email", link_path: edit_role_committee_members_path %></th>
				<th><%= sort_link "committee_position", title: "Current Role", link_path: edit_role_committee_members_path, default: true %></th>
				<th>New Role</th>
				<th></th>
			</thead>

			<tbody class="table-striped narrow">
				<% @members.each do |m| %>
					<tr>
						<td><%= m.first_name %></td>
						<td><%= m.last_name %></td>
						<td><%= m.address_1 %></td>
						<td><%= m.email %></td>
						<td><%= m.membership.committee_position %></td>
						<td>
							<%= form_for(m, url: update_role_committee_members_path) do |ff| %>
								<%= fields_for :membership do |f| %>
									<%= hidden_field_tag 'id', m.id %>
									<div style="display: inline-block"><%= f.collection_select :committee_position, @committee_positions_list, :to_s, :to_s, {include_blank: true}, {class: 'form-control'} %></div>
								<% end %>
								<div style="display: inline-block"><%= ff.submit "Assign", id: "table-btn", class: "btn member-btn" %></div>
							<% end %>
						</td>

					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/committee/members/index.html.erb
<% provide(:title, 'Membership Database') %>
<div class="top-border"></div>
	<div class="row row-top">
		<div class="container">
			<h1>Membership Database</h1>
			<p><%= back_link(members_path(@member)) %></p>
			<% flash.each do |message_type, message| %>
	    	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	 		<% end %>
			<%= form_tag(multiple_committee_members_path, multipart: true)  do %>
			<%= button_tag "Edit Selected Members", name: 'route_to[edit]', class: "btn member-btn" %>	
				<div class="btn-group">
					<button type="button" class="btn member-btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Export <span class="caret"></span></button>
					<ul class="dropdown-menu">
						<li><%= link_to "Entire Database", export_all_committee_members_path(format: "csv"), class: "dd-btn btn member-btn" %></li>
						<li><%= link_to "For BMC - all paid members", export_bmc_committee_members_path(format: "csv"), class: "dd-btn btn member-btn" %></li>
					</ul>
				</div>
				<div class="btn-group">
					<button type="button" class="btn member-btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Export Selected <span class="caret"></span></button>
					<ul class="dropdown-menu">
						<li><%= button_tag "All Data", name: 'route_to[export_all]', class: "dd-btn btn member-btn" %></li>
						<li><%= button_tag "Member Data", name: 'route_to[members]', class: "dd-btn btn member-btn" %></li>
						<li><%= button_tag "Membership Data", name: 'route_to[membership]', class: "dd-btn btn member-btn" %></li>
						<li><%= button_tag "Emergency Contact Data", name: 'route_to[em_cont]', class: "dd-btn btn member-btn" %></li>
						<li><%= button_tag "Data for BMC", name: 'route_to[bmc]',data: { confirm: "Note: Members whose fees have not been marked as received will not be exported."}, class: "dd-btn btn member-btn" %></li>
					</ul>
				</div>
			<div class="table-responsive">
				<table class="table table-hover membership-table">
					<thead>
						<th></th>
						<th><%= sort_link "first_name", title: "First Name", link: committee_members_path %></th>
						<th><%= sort_link "last_name", title: "Last Name", link: committee_members_path %></th>
						<th><%= sort_link "bb_name", title: "BB Name", link: committee_members_path %></th>
						<th><%= sort_link "membership_type", title: "Type", link: committee_members_path %></th>
						<th><%= sort_link "subs_paid", title: "Subs Paid?", link: committee_members_path %></th>
						<th><%= sort_link "fees_received_on", title: "Last Paid", link: committee_members_path %></th>
						<th><%= sort_link "welcome_pack_sent", title: "Welcome Pack?", link: committee_members_path %></th>
						<th><%= sort_link "receive_emails", title: "Mailing List?", link: committee_members_path %></th>
						<th><%= sort_link "created_at", title: "Signed Up", link: committee_members_path %></th>
						<th></th>
						<th></th>
						<th></th>
					</thead>

					<tbody>
						<% @members.each do |m| %>
						<tr>
							<td><%= check_box_tag "selected[]", m.id, checked=m.selected, class: 'check-box' %></td>
							<td><%= m.first_name %></td>
							<td><%= m.last_name %></td>
							<td><%= m.bb_name %></td>
							<td><%= m.membership.membership_type %></td>
							<td><%= readable_boolean(m.membership.subs_paid).html_safe %></td>
							<td><% if !m.membership.fees_received_on.nil? %><%= m.membership.fees_received_on.strftime("%d/%m/%Y") %><% end %></td>
							<td><%= readable_boolean(m.membership.welcome_pack_sent).html_safe %></td>
							<td><%= readable_boolean(m.receive_emails).html_safe %></td>
							<td><%= created_at(m) %></td>
							<td><%= link_to "view", committee_member_path(m) %></td>
							<td><%= link_to "edit", edit_committee_member_path(m) %></td>
							<td><%= link_to "delete", committee_member_path(m), method: :delete, data: { confirm: "You are about to delete #{m.full_name} from the database."} %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/committee/members/multiple.html.erb
<% provide(:title, "Update Multiple Members") %>
<% provide(:path, update_multiple_committee_members_path) %>
<% provide(:button_text, "Update Members") %>
<div class="top-border"></div>
<div class="row-top">
	<div class="row">	
		<div class="col-md-4 col col-md-offset-2 no-padding">
			<h1>Update Multiple Members</h1>
			<p><%= back_link(saved_sort_or(committee_members_path)) %></p>
		</div>
	</div>
	<div class="row">	
		<div class="col-md-4 col col-md-offset-2">
			<%=form_for(@members_to_edit, url: yield(:path)) do |ff|%>
				<%= fields_for :membership do |f| %>
					<%= f.label :membership_type %>
					<%= f.collection_select :membership_type, Membership::MEMBERSHIP_TYPES, :to_s, :to_s, {include_blank: true}, {class: 'form-control'} %>
					<%= f.label :welcome_pack_sent, 'Welcome pack sent' %><b>?</b>
					<%= f.select :welcome_pack_sent, [["Yes", true], ["No", false]], {include_blank: true}, {class: 'form-control'} %>
					<%= f.label :fees_received_on %>
					<%= f.date_field :fees_received_on, class: 'form-control' %>
				<% end %>
		</div>
		<div class="col-md-4">
			<p><b>You are updating the following <% unless @no_of_members_to_edit < 2 %><%= @no_of_members_to_edit %><% end %> <%= "member".pluralize(@no_of_members_to_edit) %>:</b></p>
			<ul>
				<% @members_to_edit.each do |m| %>
					<%= hidden_field_tag 'member_ids[]', m.id %>
					<li><b><%= m.first_name %> <%= m.last_name %></b></li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col col-md-offset-2" style="margin-top: 20px;">
			<%= ff.submit "Update Members", class: "btn btn-lg user-btn full-width"%>
		</div>
	</div>
			<% end %>
	</div>
</div>			

app/views/committee/members/show.html.erb
<% provide(:title, "Member Details") %>
<div class="top-border"></div>
<div class="row-top">
	<div class="row">	
		<div class="col-md-8 col col-md-offset-2">
			<h1>Information for <i><b><%=@member.first_name %> <%=@member.last_name %></i></b></h1>
			<p><%= back_link(committee_members_path) %></p>
		</div>
	</div>
	<div class="row">	
		<div class="col-md-3 col-md-offset-2">
			<h3>Address</h3>
			<p>
				<%=@member.first_name %> <%=@member.last_name %><br/>
				<%= @member.address_1 %><br/>
				<% if @member.address_2.present? %><%= @member.address_2 %><br/><% end %>
				<% if @member.address_3.present? %><%= @member.address_3 %><br/><% end %>
				<%= @member.town %><br/>
				<%= @member.county %><br/>
				<%= @member.postcode %><br/>
			</p>
			<p>
				<%= @member.email %><br/>
				<% if @member.home_phone.present? %><%= @member.home_phone %><br/><% end %>
				<% if @member.mob_phone.present? %><%= @member.mob_phone %><% end %>
			</p>
		</div>
		<div class="col-md-3">
			<h3>Emergency Contact</h3>
			<p>Relationship: 
				<%= @member.emergency_contact.relationship %><br/>
				<%= @member.emergency_contact.name %><br/>
				<%= @member.emergency_contact.primary_phone %><br>
				<% if @member.emergency_contact.secondary_phone %><%= @member.emergency_contact.secondary_phone %><% end %>
			</p>
			<p>
				<%= @member.emergency_contact.address_1 %><br/>
				<% if @member.emergency_contact.address_2.present? %><%= @member.emergency_contact.address_2 %><br/><% end %>
				<% if @member.emergency_contact.address_3.present? %><%= @member.emergency_contact.address_3 %><br/><% end %>
				<%= @member.emergency_contact.town %><br/>
				<%= @member.emergency_contact.postcode %><br/>
			</p>
		</div>
		<div class="col-md-3">
			<h3>Membership</h3>
			<p>
				<% if @member.membership.committee_position.present? %><b>Committee Role:</b><br/><%= @member.membership.committee_position %><br/><% end %>
			</p>
			<p>
				<% if !@member.bb_name.nil? %><b>Bulletin Board Name:</b><br/>
				<%= @member.bb_name %><% end %>
			</p>			
			<p><b><%= @member.membership.membership_type %> Member</b>
				<% if @member.membership.made_full_member? %><b>since:</b><br/>
				<%= @member.membership.made_full_member.strftime("%d/%m/%Y") %><% end %>
			</p>			
							
			<% if @member.membership.welcome_pack_sent %>
				<p><b>Welcome pack sent?</b><br/> Yes</p>
			<% end %>

			<p><b>Paid for current year?</b><br/> 
				<% if @member.membership.subs_paid %>Yes. Fees received on: 
				<%= @member.membership.fees_received_on.strftime("%d/%m/%Y") %>
				<% else %>
					No
				<% end %>
			</p>
			<% if !@member.membership.bmc_number.nil? %>
				<p><b>BMC number</b><br/> <%= @member.membership.bmc_number %></p>
			<% end %>
		</div>
		<div class="col-md-8 col col-md-offset-2">
			<% if !@member.experience.nil? %><br>
				<h3>Mountaineering Experience</h3><p><%= @member.experience %></p>
			<% end %>
		</div>
	</div>
</div>