config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/home', to: 'static_pages#home'
  get '/membership', to: 'static_pages#membership'
  get '/application', to: 'members#new'
  post '/application', to: 'members#create'
  get '/benefits', to: 'static_pages#benefits'
  get '/pay', to: 'static_pages#pay'
  get '/handbook', to: 'static_pages#handbook'
  get '/handbook_download', to: 'static_pages#handbook_download'
  get '/meets', to: 'static_pages#meets'
  get '/calendar', to: 'static_pages#calendar'
  get '/meetslist', to: 'static_pages#ical_feed'
  get '/booking', to: 'static_pages#booking'
  get '/galleries', to: 'static_pages#galleries'
  get '/help', to: 'static_pages#help'
  get '/committee', to: 'static_pages#the_committee'
  get '/history', to: 'static_pages#history'
  get '/cae_amos', to: 'static_pages#cae_amos'
  get '/archives', to: 'static_pages#archives'
  get '/reports', to: 'static_pages#reports'
  get '/contact', to: 'static_pages#contact'
  get '/links', to: 'static_pages#links'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/login', to: 'static_pages#membership'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/update_attendee_status/:meet_id/:member_id', to: 'attendees#update_status', as: 'update_attendee_status'

  resources :password_resets, only: %i[new create edit update]

  resources :members do
    member do
      get 'emergency_contact', to: 'emergency_contact#edit'
      patch 'emergency_contact', to: 'emergency_contact#update'
      get 'meets', to: 'meets#edit'
      patch 'meets', to: 'meets#update'
      get 'attendees', to: 'attendees#index'
      patch 'attendees', to: 'attendees#update'
      delete 'attendees', to: 'attendees#destroy'
      get 'sign_up/:meet_id', to: 'attendees#new', as: :new_attendee
      post 'sign_up/:meet_id', to: 'attendees#create'
      patch 'email_subscribe', to: 'members#email_subscribe'
    end
  end

  namespace :committee do
    resources :emails
    get '/mailer/email_preview(/:id(.:format))', to: 'emails#email_preview', as: 'email_preview'
    get '/mailer/send_email(/:id(.:format))', to: 'emails#send_email', as: 'send_email'
    get 'past_meets', to: 'meets#past'
    resources :meets
    resources :attendees
    resources :members do
      collection do
        post :multiple
        patch :update_multiple
        get :edit_role
        patch :update_role
        get :export_all, to: 'members#all'
        get :export_bmc, to: 'members#for_bmc'
        post :export_checked, to: 'members#checked'
        get :download_file, to: 'members#download_file'
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<div class=" bottom-border"></div>
<div class="container-fluid footer">
	<div class="col-md-4 col-xs-12 footer-left">
		<p>Keep up to date with<br>Leeds Mountaineering Club</p>
		<%= link_to( image_tag("FB.png"), "https://www.facebook.com/groups/349638151786515/", target: "_blank") %>
		<%= link_to( image_tag("IG.png"), "https://www.instagram.com/leedsmountaineeringclub/?hl=en", target: "_blank") %>
		<%= link_to( image_tag("TW.png"), "https://twitter.com/mountain_eering", target: "_blank") %>
	</div>
	<div class="col-md-4 col-md-offset-4 col-xs-12 footer-right">
		<p>Copyright &copy; 2004 - <%= Date.today.year %></p>
		<p>For information on how we use data collected on you please read our <%= link_to "Privacy Policy", privacy_policy_path %>.</p>
		<p>This website uses cookies to facilitate much of the functionality for logged in users.</p>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-default">
    <div class="navbar-elements">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav navbar-left">
        <li id="logo"><%= image_tag('LMC_logo.gif')+"Leeds Mountaineering Club" %></li>
      </ul>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Bulletin Board", bb_url %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Membership <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
            <li><%= link_to "My Details", membership_path(@member) %></li>
              <% else %>
            <li><%= link_to "Join or Log In", membership_path %></li>
              <% end %>
            <li><%= link_to "Why Join?", benefits_path %></li>
            <li><%= link_to "Pay Your Subs", pay_path %></li>
            <li><%= link_to "Members Handbook", handbook_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Meets <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "When and Where we Meet", meets_path %></li>
            <li><%= link_to "Meets Calendar", calendar_path %></li>
            <li><%= link_to "Booking on a Meet", booking_path %></li>
            <!--<li><%= link_to "Galleries", '#' %></li>-->
          </ul>
        </li>
        <li><%= link_to "Blog", blog_url, target: :_blank %></li>
        <li class="dropdown">
          <a href='#' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">About<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "How Do I?", help_path %></li>
            <li><%= link_to "The Committee", committee_path %></li>
            <li><%= link_to "Contact Us", contact_path %></li>
            <li><%= link_to "Club History & Archives", archives_path %></li>
            <li><%= link_to "Links", links_path %></li>
            <li><%= link_to "Privacy Policy", privacy_policy_path%></li>
          </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </nav>
</div>

app/views/layouts/_rails_default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8"> <meta name=viewport content="width=device-width, initial-scale=1">
    <% if @meta_description.present? %>
      <meta name="description" content="<%= @meta_description %>" />
    <% end %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a11b0039af.js" crossorigin="anonymous"></script>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<div class="container-fluid bkgrnd">
      <%= render 'layouts/header' %>
  	  <%= yield %>
     	<%= render 'layouts/footer' %>
    </div>
  </body>
</html>