config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/home', to: 'static_pages#home'
  get '/membership', to: 'static_pages#membership'
  get '/application', to: 'members#new'
  post '/application', to: 'members#create'
  get '/benefits', to: 'static_pages#benefits'
  get '/pay', to: 'static_pages#pay'
  get '/handbook', to: 'static_pages#handbook'
  get '/handbook_download', to: 'static_pages#handbook_download'
  get '/meets', to: 'static_pages#meets'
  get '/calendar', to: 'static_pages#calendar'
  get '/meetslist', to: 'static_pages#ical_feed'
  get '/booking', to: 'static_pages#booking'
  get '/galleries', to: 'static_pages#galleries'
  get '/help', to: 'static_pages#help'
  get '/committee', to: 'static_pages#the_committee'
  get '/history', to: 'static_pages#history'
  get '/cae_amos', to: 'static_pages#cae_amos'
  get '/archives', to: 'static_pages#archives'
  get '/reports', to: 'static_pages#reports'
  get '/contact', to: 'static_pages#contact'
  get '/links', to: 'static_pages#links'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/login', to: 'static_pages#membership'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/update_attendee_status/:meet_id/:member_id', to: 'attendees#update_status', as: 'update_attendee_status'

  resources :password_resets, only: %i[new create edit update]

  resources :members do
    member do
      get 'emergency_contact', to: 'emergency_contact#edit'
      patch 'emergency_contact', to: 'emergency_contact#update'
      get 'meets', to: 'meets#edit'
      patch 'meets', to: 'meets#update'
      get 'attendees', to: 'attendees#index'
      patch 'attendees', to: 'attendees#update'
      delete 'attendees', to: 'attendees#destroy'
      get 'sign_up/:meet_id', to: 'attendees#new', as: :new_attendee
      post 'sign_up/:meet_id', to: 'attendees#create'
      patch 'email_subscribe', to: 'members#email_subscribe'
    end
  end

  namespace :committee do
    resources :emails
    get '/mailer/email_preview(/:id(.:format))', to: 'emails#email_preview', as: 'email_preview'
    get '/mailer/send_email(/:id(.:format))', to: 'emails#send_email', as: 'send_email'
    get 'past_meets', to: 'meets#past'
    resources :meets
    resources :attendees
    resources :members do
      collection do
        post :multiple
        patch :update_multiple
        get :edit_role
        patch :update_role
        get :export_all, to: 'members#all'
        get :export_bmc, to: 'members#for_bmc'
        post :export_checked, to: 'members#checked'
        get :download_file, to: 'members#download_file'
      end
    end
  end
end

app/controllers/committee/members_controller.rb
class Committee::MembersController < Committee::BaseController
	helper_method :sort_column, :sort_direction
	
	include MembersExports
	include MembersMultiple

	def index
		@members = Member.joins(:membership).order("#{sort_column} #{sort_direction}")
		recall_selected(@members)
	end

	def show
		remember_selected
		@member = Member.find(params[:id])
	end

	def edit
		remember_selected
		@member_to_edit = Member.find(params[:id])
	end

	def update
  	@member_to_edit = Member.find(params[:id])
  	if @member_to_edit.update_attributes(member_params)
  		flash[:success] = "Member updated"
      redirect_to committee_members_path
  	else
  		render 'edit'
  	end
  end

  def multiple
  	remember_selected
  	if params[:selected].nil?
	  	flash[:danger] = "No members selected."
	  	@members = Member.joins(:membership).order("#{sort_column} #{sort_direction}")
	  	redirect_to committee_members_path
	  	return
	  else
	  	case route_to params
	  	when :edit
	  		edit_multiple
	  	else
	  		export
	  	end
	  end
  end

  def edit_role
		@members = Member.joins(:membership).order("#{sort_column} #{sort_direction}")
		@committee_positions_list = committee_positions_list
  end

  def update_role
  	@member_to_assign_role = Member.find(params[:id])
  	@member_to_remove_role = Member.joins(:membership).find_by(memberships: {committee_position: params[:membership][:committee_position]})
  	if params[:membership][:committee_position] == "- remove role -"
  		if @member_to_assign_role.membership.update_attributes!(committee_position: nil)
  			flash[:success] = "#{@member_to_assign_role.first_name} #{@member_to_assign_role.last_name} is no longer on the committee"
  		end
  	else
  		@member_to_remove_role.membership.update_attributes!(committee_position: nil) unless @member_to_remove_role.nil?
  	end
  	
  	if @member_to_assign_role.membership.update_attributes(roles_params)
  		flash[:success] = "#{@member_to_assign_role.first_name} #{@member_to_assign_role.last_name} is now the #{@member_to_assign_role.membership.committee_position}"
  	else
  		flash.now[:danger] = "Failed to assign role. Pleae try again or contact the site admin."
  	end
		redirect_to saved_sort_or(committee_members_path)
  end

  def destroy
  	Member.find(params[:id]).destroy
  	flash[:success] = "Member removed from database."
  	redirect_to committee_members_path
  end
end

private

def member_params
	params.require(:member).permit(:address_1,
	  														 :address_2,
	  														 :address_3,
	  														 :town,
	  														 :postcode,
	  														 :country,
	  														 :phone,
	  														 :email,
	  														 :dob,
	  														 :bb_name,
	  															membership_attributes: [
	  																:bmc_number, 
	  																:membership_type, 
	  																:welcome_pack_sent,
	  																:fees_received_on, 
	  																:notes, 
	  																:id ]
	  														)
	end

	def membership_params
		params.require(:membership).permit(:bmc_number, :membership_type, :welcome_pack_sent,:fees_received_on, :notes)
	end

	def roles_params
		params.require(:membership).permit(:committee_position)
	end

	def sort_column(default="last_name")
		if 
			Member.column_names.include?(params[:sort])
			return params[:sort]
		elsif 
			Membership.column_names.include?(params[:sort])
			return params[:sort]
		else
			default
		end
	end

	def sort_direction(default = "asc")
		%w[asc desc].include?(params[:direction]) ? params[:direction] : default
	end

	def route_to params
		params[:route_to].keys.first.to_sym unless params[:route_to].nil?
	end

	def committee_positions_list
		["Chair",
		"Treasurer",
		"Meets Secretary",
		"Membership Secretary",
		"Communications Secretary",
		"Social Secretary",
		"Climbing Co-ordinator",
		"Walking Co-ordinator",
		"Ordinary Member",
		"Extra Ordinary Member",
		"Member Without Portfolio",
		"",
		"site admin",
		"- remove role -"]
	end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :logged_in_member, only: [:show, :edit, :update]
  before_action :correct_member, only: [:show, :edit, :update]

  include MembersHelper
  helper_method :committee_member?

	def show
    @member = Member.find(params[:id])
    @future_meets = all_future_meets
	end

  def new
  	@member = Member.new
    @meta_description = "Application form to join the Leeds Mountaineering Club."
  end

  def create
    @member = Member.new(member_params)
    verified = verify_recaptcha(model: @member)
    if verified && @member.save
  		log_in @member
      @member.send_welcome_email
      send_application_notification
  		redirect_to member_path(@member)
    else
      if !verified
        @verify_error = "Are you a robot?"
      end
  		render 'new'
  	end
  end

  def update
#  	@member = Member.find(params[:id])
  	if @member.update_attributes(member_params)
  		flash[:success] = "Details updated"
      redirect_to @member
  	else
  		render 'edit'
  	end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def index
    if logged_in?
      redirect_to current_user
    else
      redirect_to login_url
    end
  end

  def destroy
    Member.find(params[:id]).destroy
    flash[:success] = "Your information has been removed."
    redirect_to root_url
  end

  def email_subscribe
    @member = Member.find(params[:id])
    redirect_to @member if @member.toggle!(:receive_emails)
  end

  private

	  def member_params
	  	params.require(:member).permit(:title,
                                   :first_name,
	  															 :last_name,
	  															 :address_1,
	  															 :address_2,
	  															 :address_3,
	  															 :town,
                                   :county,
	  															 :postcode,
	  															 :country,
	  															 :mob_phone,
                                   :home_phone,
	  															 :email,
	  															 :dob,
	  															 :experience,
                                   :bb_name,
	  															 :accept_risks,
                                   :receive_emails,
	  															 :password, 
	  															 :password_confirmation,
                                   membership_attributes: [
                                    :bmc_number,
                                    :id ])
	  end

  def send_application_notification
    MemberMailer.application_notification(@member).deliver_now
  end

end

app/helpers/members_helper.rb
module MembersHelper

	def membership_level(member)
		if member.membership.committee_position
			"#{member.membership.committee_position}"
		else
			"#{member.membership.membership_type} Member"
		end
	end

	def committee_member?(member)
		!member.membership.committee_position.nil?
	end

	def latest_update(member)
		update = [member.updated_at, member.membership.updated_at].max
		update.strftime("%d/%m/%Y")
	end

	def created_at(member)
		member.created_at.strftime("%d/%m/%Y")
	end

	def updated_at(member)
		member.updated_at.strftime("%d/%m/%Y")
	end

	def new_member?(member)
		membership_level(member) == "Provisional (unpaid) Member"
	end

	def em_contact?(member)
		true if member.emergency_contact.primary_phone.nil?
	end
end

app/views/members/_form.html.erb
<%= form_for(@member, url: yield(:path)) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="row">
		<div class="col-md-4">
			<h3>You</h3>
			<%= f.label :first_name %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :first_name) %></p>
			<%= f.text_field :first_name, class: 'form-control' %>
						
			<%= f.label :last_name %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :last_name) %></p>
			<%= f.text_field :last_name, class: 'form-control' %>

			<%= f.label :dob, 'Date of Birth' %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :dob) %></p>
			<%= f.date_field :dob, class: 'form-control' %>

			<%= f.label :experience %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :experience) %></p>
			<%= f.text_area :experience, size: "4x4", placeholder: "Please provide a brief resume of your mountaineering experience including membership of other clubs.", class: 'form-control' %>

			<%= f.label :bb_name, 'Bulletin Board Name' %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :bb_name) %></p>
			<%= f.text_field :bb_name, placeholder: "Username if you've registered on the Bulletin Boards.", class: 'form-control' %>

			<%= f.fields_for :membership do |m| %>
				<%= m.label :bmc_number, 'BMC number' %>
				<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :bmc_number) %></p>
				<%= m.text_field :bmc_number, class: 'form-control' %>
			<% end %>
		</div>

		<div class="col-md-4">
			<h3>Address</h3>
			<%= f.label :address_1 %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :address_1) %></p>
			<%= f.text_field :address_1, class: 'form-control' %>
							
			<%= f.label :address_2 %>
			<%= f.text_field :address_2, class: 'form-control' %>
						
			<%= f.label :address_3 %>
			<%= f.text_field :address_3, class: 'form-control' %>

			<%= f.label :town %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :town) %></p>
			<%= f.text_field :town, class: 'form-control' %>

			<%= f.label :county %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :county) %></p>
			<%= f.text_field :county, class: 'form-control' %>

			<%= f.label :postcode %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :postcode) %></p>
			<%= f.text_field :postcode, class: 'form-control' %>

			<%= f.label :country %>
			<%= f.collection_select :country, Member::COUNTRIES, :to_s, :to_s, {}, {class: 'form-control'} %>
		</div>

		<div class="col-md-4">
			<h3>Contact Details</h3>
			<%= f.label :email %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :email) %></p>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :home_phone %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :home_phone) %></p>
			<%= f.phone_field :home_phone, class: 'form-control' %>

			<%= f.label :mob_phone %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :mob_phone) %></p>
			<%= f.phone_field :mob_phone, class: 'form-control' %>

			<h3 style="margin-bottom: 18px">Password</h3>
			<%= f.label :password %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :password) %></p>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<p id='error_explanation' style="margin: -1px 0"><%= show_errors(@member, :password_confirmation) %></p>
		  <%= f.password_field :password_confirmation, class: 'form-control' %>
		</div>
	</div>
		
	<div class="row">
		<div class="col-md-12 text-center radio-inline" style="border:solid 1px #bbb; font-weight: bold;">
			<p class="text-center"><%= Member::PARTICIPATION_STATEMENT %></p>

			<span class="input-group-addon center-block" style="border: none; background-color: inherit; width:auto">
				<p id='error_explanation'><%= show_errors(@member, :accept_risks) %></p>
				<%= f.check_box :accept_risks, { class: "radio-inline", style: "width: auto" } %>
				<%= f.label :accept_risks, "I accept the risks." %>
							
			</span>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center radio-inline" style="border:solid 1px #bbb; font-weight: bold;">
			<p>The club sends out newsfeeds, usually once a month, with information about past and up coming meets. We may also send out subs reminders at the start of the year if you haven't paid your subs. You can opt in or out of receiving these emails at any point after completing this application.</p>
			<span class="input-group-addon center-block" style="border: none; background-color: inherit; width:auto">
				<%= f.check_box :receive_emails, { class: "radio-inline", style: "width: auto" } %>
				<%= f.label :receive_emails, "I want to receive emails from the club." %>
			</span>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center radio-inline" style="border:solid 1px #bbb; font-weight: bold;">
			<p class="text-center">By completing your application below you are accepting the terms of our <%= link_to "Privacy Policy", privacy_policy_path %>.</p>
		</div>
	</div>
	<div>
		<div class="col-md-6 col-md-offset-3 text-center" style="margin-top: 20px; display: inline-block">
			<% if @verify_error%>
				<p id='error_explanation'><%= @verify_error %></p>
			<% end%>
			<%= recaptcha_tags %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3" style="margin-top: 20px;">
		  <%= f.submit yield(:button_text), class: "btn btn-lg user-btn full-width" %>
		</div>
	</div>
<% end %>

app/views/members/_no_emergency_contact.html.erb
<div class="panel panel-danger">
	<div class="panel-heading">
		<h3>You haven't added an emergency contact</h3>
	</div>
	<div class="panel-body">
		<h4>Please Add an Emergency Contact</h4>
		<p>We need and emergency contact for you just in case something happens on a meet or when you're out with another club member. We also might need to supply it to an instuctor or training course should you sign up for one provided through the club.</p>
		<%= link_to "Add Emergency Contact", emergency_contact_member_path, class: "btn member-btn" %>
	</div>
</div>

app/views/members/_welcome.html.erb
<div class="panel panel-success">
	<div class="panel-heading">
		<h2>Welcome to the Leeds Mountaineering Club!</h2>
	</div>
	<div class="panel-body">
		<h4>Thanks for joining the club. There's just a few things left to do...</h4>
		<br>
		<h4>Add your emergency contact information</h4>
		<p>We need this just in case something happens on a meet or when you're out with another club member. We also might need to supply it to an instuctor or training course should you sign up for one provided through the club.</p>
		<%= link_to "Add / Edit Emergency Contact", emergency_contact_member_path, class: "btn member-btn" %>
		<h4>Pay the membership fee</h4>
		<p>To pay the membership fee you can pay by Paypal or by bank transfer. Alternatively you can send a cheque to the treasurer or other committee member either in person or by post. You are welcome to attend a few day or evening meets before paying the membership fee if you wish.</p>
		<h4>Sign up to use the <a href="http://leedsmc.org/bulletinboard/" target="_blank">Bulletin Boards</a></h4>
		<p>This is where all the meets and other club activities are organised and discussed. At the moment you need a different login to the one you created on your application form - create this when you register.</p>
		<h4>I'm not a new member - why can I see this message?</h4>
		<p>If you can see this message then it means we haven't marked your membership fee as paid since you joined. If it's been a while since you paid then it's probably best to contact us to check we've received it.</p>
	</div>
</div>

app/views/members/edit.html.erb
<% provide(:title, "Change Your Details") %>
<% provide(:path, member_path(@member)) %>
<% provide(:button_text, "Update Information") %>
<div class="row row-btm top-border">
	<div class="container">
		<h1>Update Your Information</h1>
		<p><%= back_link(members_path(@member)) %></p>
		<%= link_to "Add/change your emergency contact", emergency_contact_member_path, class: "btn member-btn" %>
		<% unless @member.receive_emails %>
			<%= link_to "Subscribe to all club emails", email_subscribe_member_path(@member), :method => :patch, class: "btn member-btn" %>
		<% else %>
			<%= link_to "Unsubscribe from all club emails", email_subscribe_member_path(@member), :method => :patch, class: "btn member-btn" %>
		<% end %>
		<%= link_to "Remove my membership", member_path(@member),method: :delete, data: { confirm: "This will permanently remove all your information. You will no longer be a member of the Leeds Mountaineering Club."}, id: "danger-btn", class: "btn member-btn pull-right" %>

		<%= render 'form' %>
	</div>
</div>

app/views/members/new.html.erb
<% provide(:title, 'Application Form') %>
<% provide(:path, application_path) %>
<% provide(:button_text, 'Submit Application') %>

<div class="row row-btm top-border">
	<div class="container">
		<h1>Application Form</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/members/show.html.erb
<% provide(:title, @member.first_name + " " + @member.last_name) %>
<div class="top-border"></div>
<div class="row-top">
	<div class="container">
		<h1><%= @member.first_name %> <%= @member.last_name %></h1>
		<h4><%= membership_level(@member) %></h4>
		<% unless @member.receive_emails %>
			<span class="email-opt-in">
				<%= link_to email_subscribe_member_path(@member), :method => :patch, class: "btn member-btn-small" do %>
					<i class="fas fa-envelope-open-text"></i> Opt in
				<% end %>
				You are not currently on the club newsletter mailing list.
			</span>
		<% else %>
			<span class="email-opt-in">
				<%= link_to email_subscribe_member_path(@member), :method => :patch, class: "btn member-btn-small" do %>
					<i class="far fa-envelope"></i> Opt out
				<% end %>
				You are on the club newsletter mailing list.
			</span>
		<% end %>
		<% if @member.bb_name %>
			<p>Your username for the Bulletin Board is: <b><%= @member.bb_name %></b></p>
		<% end %>
		<% flash.each do |message_type, message| %>
	    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	  <% end %>
		<% if committee_member?(@member) %>
			<div class="buttons-menu">
				<%= link_to "Membership Database", committee_members_path, class: "btn member-btn" %> 
				<%= link_to "Meets Calendar", committee_meets_path, class: "btn member-btn" %>
				<%= link_to "Send Emails", committee_emails_path, class: "btn member-btn" %>
				<%= link_to "Change Committee Members", edit_role_committee_members_path, class: "btn member-btn" %>
			</div>
		<% end %>

		<% if new_member?(@member) %>
			<%= render 'welcome' %>
		<% elsif em_contact?(@member) %>
			<%= render 'no_emergency_contact' %>
		<% end %>
	</div>
	<div class="container no-padding">
		<div class="col-md-4 col-sm-4 col-xs-12">
			<div class="info-box">
					<h3>My Meets</h3>
					<%= link_to "Sign Up!", attendees_member_path(@member), class: "btn member-btn sign-up-btn" %>
					<% if @member.meets.any? %>
						<% @member.meets.order(meet_date: :asc).each do |m| %>
							<% if m.meet_date >= Date.today %>
								<div class="meet-box" >
									<p class="meet-box__date"><%= m.meet_date.strftime("%d/%m/%Y") %></p>
									<p class="meet-box__location"><%= m.location %></p>
									<% if meet_leader?(@member, m)%>
										<%= link_with_arrow(meets_member_path(@member, {:meet => {:id => m.id}}), "Meet Leader") %>
									<% else %>
                    <%= link_with_arrow(new_attendee_member_path(@member, m), "Info") %>
                  <% end %>
                  <% if m.bb_url != "" %><br/><%= link_with_arrow(m.bb_url, "Bulletin Board Thread", "meet-box__bb-link") %><% end %>
								</div>
							<% end %>
						<% end %>
					<% end %>
			</div>
		</div>
		<div class="lead col-md-4 col-sm-4 col-xs-12">
			<div id="box-1" class="info-box">
				<h3>My Details</h3>
				<%= link_to @member.email.present? ? "Edit" : "Add", edit_member_path(@member), class: "btn member-btn" %>
				<p>
					<%= @member.email %><br>
					<% if @member.home_phone.present? %><%= @member.home_phone %><br><% end %>
					<% if @member.mob_phone.present? %><%= @member.mob_phone %><% end %>
				</p>
				<p>
					<%= @member.address_1 %><br>
					<% if @member.address_2.present? %><%= @member.address_2 %><br><% end %>
					<% if @member.address_3.present? %><%= @member.address_3 %><br><% end %>
					<%= @member.town %><br>
					<%= @member.county %><br>
					<%= @member.postcode %><br>
				</p>
			</div>
		</div>
		<div class="lead col-md-4 col-sm-4 col-xs-12">
			<div class="info-box">
				<h3>My Emergency Contact</h3>
				<%= link_to em_contact?(@member) ? "Add" : "Edit", emergency_contact_member_path, class: "btn member-btn" %>
				<% if !em_contact?(@member)%>
					<p>
						<%= @member.emergency_contact.relationship %><br>
						<%= @member.emergency_contact.name %><br>
						<%= @member.emergency_contact.primary_phone %><br>
						<% if @member.emergency_contact.secondary_phone %><%= @member.emergency_contact.secondary_phone %><% end %>
					</p>
					<p>
						<%= @member.emergency_contact.address_1 %><br>
						<% if @member.emergency_contact.address_2.present? %><%= @member.emergency_contact.address_2 %><br><% end %>
						<% if @member.emergency_contact.address_3.present? %><%= @member.emergency_contact.address_3 %><br><% end %>
						<%= @member.emergency_contact.town %><br>
						<%= @member.emergency_contact.postcode %><br>
					</p>
				<% end %>
			</div>
		</div>
	</div>
</div>